// src/utils/format.ts
import { formatEther } from "viem";

/**
 * Recursively converts objects containing BigInts to serializable strings.
 * Ensures that data can safely be sent over JSON or stored without losing precision.
 */
export function toSerializable(obj: any): any {
  if (typeof obj === "bigint") return obj.toString();
  if (Array.isArray(obj)) return obj.map(toSerializable);
  if (obj && typeof obj === "object") {
    return Object.fromEntries(
      Object.entries(obj).map(([k, v]) => [k, toSerializable(v)])
    );
  }
  return obj;
}

/**
 * Formats a BigInt ETH value to a human-readable string with 4 decimal places.
 * Standardizes ETH display across the app for balances and transactions.
 */
export function formatNumber(number: bigint): string {
  return parseFloat(Number(formatEther(number)).toFixed(4)).toString();
}

/**
 * Shortens a blockchain address for display purposes.
 * Defaults to 6 chars start / 4 chars end, improving UI readability.
 */
export function truncateAddress(address: string, start = 6, end = 4): string {
  if (!address) return "";
  return `${address.slice(0, start)}...${address.slice(-end)}`;
}

/**
 * Formats a UNIX timestamp (seconds) to a localized date string.
 * Provides consistent human-readable date display in the UI.
 */
export function formatDate(date: bigint): string {
  return new Date(Number(date) * 1000).toLocaleString("en-US", {
    year: "numeric",
    month: "numeric",
    day: "numeric",
    hour: "numeric",
    minute: "2-digit",
  });
}

/**
 * Converts seconds, milliseconds, or BigInt timestamps to milliseconds.
 */
const toMillis = (v: number | string | bigint | undefined): number => {
  if (v === undefined || v === null) return 0;
  const n = typeof v === "bigint" ? Number(v) : Number(v);
  return n > 1e12 ? n : n * 1000;
};

/**
 * Computes remaining time until a deadline, factoring the delay penalty.
 * Returns a formatted string or "Withdrawable" if the deadline has passed.
 */
export function getTimeRemaining(
  deadline: number | string | bigint | undefined,
  delay: number | string | bigint | undefined
): string {
  const deadlineMs = toMillis(deadline);
  const delayMs = toMillis(delay);
  const end = deadlineMs + delayMs;
  const remaining = end - Date.now();
  const timeRemaining = formatTime(Math.floor(remaining / 1000));
  return remaining > 0 ? timeRemaining : "Withdrawable";
}

/**
 * Converts a string into a URL-friendly slug.
 * Standardizes route and filter strings across the app.
 */
export function slugify(str: string): string {
  return str.toLowerCase().replace(/\s+/g, "-").replace(/[^a-z0-9-]/g, "");
}

/**
 * Parses a slug generated by slugify and extracts the ID (last segment).
 * Returns the ID as a serializable BigInt or null if parsing fails.
 */
export function parseSlug(slug: string) {
  if (!slug) return null;
  const parts = slug.split("-");
  const rawId = parts.pop();
  try {
    return toSerializable({ id: BigInt(rawId!) });
  } catch {
    return null;
  }
}

/**
 * Formats a duration in seconds into a human-readable string.
 * Example: 90061 seconds → "1 day 1 hr 1 min"
 */
export function formatTime(seconds: number): string {
  const days = Math.floor(seconds / 86400);
  const hours = Math.floor((seconds % 86400) / 3600);
  const minutes = Math.floor((seconds % 3600) / 60);

  const parts: string[] = [];
  if (days > 0) parts.push(`${days} day${days > 1 ? "s" : ""}`);
  if (hours > 0) parts.push(`${hours} hr${hours > 1 ? "s" : ""}`);
  if (minutes > 0) parts.push(`${minutes} min${minutes > 1 ? "s" : ""}`);

  return parts.join(" ") || "0 min";
}
